include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - always_specify_types
    - public_member_api_docs # Enforces doc comments