name: universal_file_viewer
description: "A Flutter package to preview images, videos, PDFs, Word, Excel, CSV, PPT, and more."
version: 0.0.11
homepage: https://github.com/Shonu72/
repository: https://github.com/Shonu72/universal_file_viewer
issue_tracker: https://github.com/Shonu72/universal_file_viewer/issues?q=is%3Aissue%20state%3Aopen%20

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  macos:

dependencies:
  flutter:
    sdk: flutter

  open_file: ^3.5.10
  video_player: ^2.9.3
  pdfrx: ^1.1.11
  pdf: ^3.10.8
  excel: ^4.0.6
  path: ^1.9.1
  path_provider: ^2.1.5
  archive: ^3.6.1
  xml: ^6.5.0
  csv: ^6.0.0
  markdown: ^7.3.0
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3+4
  shimmer: ^3.0.0
  docx_file_viewer: ^0.0.7
  ### in the near future use in case the docX owner do not merge I'll create the lib for the mean time I put the code in the word file preview
  ###     #git:
  #    #  url: https://github.com/oscarshaitan/docx_viewer
  #    #  ref: 6356e9133f41cc56205d8da0e02c3ebb94440f25


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - filepreviewer
  - widgets
  - package
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
