name: universal_file_viewer
description: "A Flutter package to preview images, videos, PDFs, Word, Excel, CSV, PPT, and more."
version: 0.0.9
homepage: https://github.com/Shonu72/
repository: https://github.com/Shonu72/universal_file_viewer

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  macos:

dependencies:
  flutter:
    sdk: flutter

  open_file: ^3.5.10
  video_player: ^2.9.3
  pdfrx: ^1.1.11
  pdf: ^3.10.8
  excel: ^4.0.6
  path: ^1.9.1
  path_provider: ^2.1.5
  archive: ^3.6.1
  xml: ^6.5.0
  csv: ^6.0.0
  markdown: ^7.3.0
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3+4
  docx_file_viewer: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_override:
  archive: ^3.6.1

